#!/usr/bin/env bash

set -euo pipefail

### Control github Usage:help
#
# Batch operations
#
#   githubctl create OWNER REPOS ...
#
#   githubctl reown OWNER NEWOWNER REPOS ...
#
#   githubctl delete OWNER REPOS ...
#
#   githubctl srename OWNER SUBSTITUTION REPOS ...
#
# Single-repo operations
#
#   githubctl rename OWNER REPO NEWREPO
#
###/doc

#%include autohelp.sh out.sh askuser.sh

#%include repo.sh runmain.sh bincheck.sh

gh:main() {
    autohelp:check "$@"

    gh:jqcheck

    local action="${1:-}"; shift || out:fail "No action specified"

    case "$action" in
    rename|reown|delete|create|srename)
        gh:getcreds
        gh:repo:"$action" "$@"
        ;;
    *)
        out:fail "Unknown action '$action'"
        ;;
    esac
}

gh:getcreds() {
    [[ -n "${GHUSER:-}" ]] || GHUSER="$(askuser:ask "Github user name")"
    [[ -n "${GHTOKEN:-}" ]] || GHTOKEN="$(askuser:password "Github Personal Access Token"; echo >&2)"
    export GHUSER GHTOKEN
}

gh:jqcheck() {
    if ! bincheck:has jq ; then
        # Poor man's filter ; never errors.
        jq() {
            grep "$1" || :
        }
    fi
}

runmain githubctl gh:main "$@"
