#!/usr/bin/env bash

set -euo pipefail

### Control github Usage:help
#
### Batch operations
#
#Create repositories:
#
#    github-do create OWNER REPOS ...
#
#Transfer repositories to another user/organisation:
#
#    github-do reown OWNER NEWOWNER REPOS ...
#
#Delete repositories:
#
#    github-do delete OWNER REPOS ...
#
#Rename by substitution:
#
#    github-do srename OWNER SUBSTITUTION REPOS ...
#
#    # e.g. github-do myuser "s/^/old-/" project1 project2 project3
#    # Renames github.com/myuser/project1 to github.com/myuser/old-project1 ,
#    #   and same for other projects listed
#
### Single-repo operations
#
#Simply rename a project literally
#
#    github-do rename OWNER REPO NEWREPO
#
#Delete a branch from a repo
#
#    github-do branch delete OWNER REPO BRANCHNAME
#
#Delete a tag on a repo remotely
#
#    github-do tag delete OWNER REPO TAGNAME
#
###/doc

#%include autohelp.sh out.sh askuser.sh bincheck.sh

#%include repo.sh refs.sh runmain.sh

gh:main() {
    autohelp:check "$@"

    gh:jqcheck

    local action="${1:-}"; shift || out:fail "No action specified"

    case "$action" in
    rename|reown|delete|create|srename)
        gh:getcreds
        gh:repo:"$action" "$@"
        ;;
    branch|tag)
        local subaction="${1:-}"; shift || out:fail "No sub-action for '$action' specified"
        case "$subaction" in
        delete)
            "gh:$action:$subaction" "$@"
            ;;
        *)
            out:fail "Unknown sub-action '$subaction'"
            ;;
        esac
        ;;
    *)
        out:fail "Unknown action '$action'"
        ;;
    esac
}

gh:getcreds() {
    [[ -n "${GHUSER:-}" ]] || GHUSER="$(askuser:ask "Github user name")"
    [[ -n "${GHTOKEN:-}" ]] || GHTOKEN="$(askuser:password "Github Personal Access Token"; echo >&2)"
    export GHUSER GHTOKEN
}

gh:jqcheck() {
    if ! bincheck:has jq ; then
        # Poor man's filter ; never errors.
        jq() {
            grep "$1" || :
        }
    fi
}

runmain github-do gh:main "$@"
